- hosts: all
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache
      tags: always
      apt: update_cache=yes
      changed_when: False
# run roles

- hosts: all
  tags: base
  become: true
  roles:
    - base

