- name: users | install shell
  tags: packages,system,settings
  apt:
    state: latest
    name:
      - zsh

- name: users | j4ck | create group
  tags: groups,j4ck,users
  group:
    name: j4ck
    state: present

- name: users | j4ck | create user
  tags: j4ck,sudo,users
  ansible.builtin.user:
    name: j4ck
    create_home: yes
    groups: j4ck,adm,audio,sudo
    append: yes
    comment: "Jack"
    password: "{{ j4ck_passwd }}"
    shell: /usr/bin/zsh

- name: users | j4ck | create user directories
  tags: dotfiles,j4ck,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: j4ck
    group: j4ck
    mode: 0700
  with_items:
    - { dir: '/home/j4ck/GIT' }
    - { dir: '/home/j4ck/.ssh' }
    - { dir: '/home/j4ck/.local' }
    - { dir: '/home/j4ck/.config/systemd/user/' }

- name: users | j4ck | copy authorized_keys
  tags: users,j4ck,ssh
  copy:
    src: users/j4ck/authorized_keys
    dest: /home/j4ck/.ssh/
    owner: j4ck
    group: j4ck
    mode: 0440

- name: users | debian | remove default account
  tags: users,j4ck,users
  user:
    name: debian
    remove: true
    state: absent

- name: users | shell | oh-my-zsh
  tags: users,j4ck,zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: '/home/j4ck/.oh-my-zsh'
    force: no
  become: yes
  become_user: j4ck

- name: users | shell | powerlevel10k
  tags: user,j4ck,zsh
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git/'
    dest: '/home/j4ck/.oh-my-zsh/themes/powerlevel10k'
    depth: 1
  become: yes
  become_user: j4ck

- name: users | shell | oh-my-tmux
  tags: user,j4ck,tmux
  git:
    repo: 'https://github.com/gpakosz/.tmux.git'
    dest: '/home/j4ck/GIT/oh-my-tmux'
  become: yes
  become_user: j4ck

- name: users | shell | oh-my-config
  tags: user,j4ck,zsh
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    owner: j4ck
    group: j4ck
    mode: 0755
  with_items:
      - { src: 'users/j4ck/p10k.zsh', dest: '/home/j4ck/.p10k.zsh' }
      - { src: 'users/j4ck/zshrc', dest: '/home/j4ck/.zshrc' }
      - { src: 'users/j4ck/tmux.conf.local', dest: '/home/j4ck/.tmux.conf.local' }
      - { src: 'users/j4ck/tmux.conf', dest: '/home/j4ck/.tmux.conf' }

- name: users | shell | powerlevel10k config
  tags: user,j4ck,zsh
  lineinfile:
    path: '/home/j4ck/.zshrc'
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME=powerlevel10k/powerlevel10k'

