- name: users | vixen | create group
  tags: groups,vixen,users
  group:
    name: vixen
    state: present

- name: users | vixen | create user
  tags: vixen,sudo,users
  user:
    name: vixen
    group: vixen
    groups: adm,audio,sudo
    state: present
    comment: "Vixen"
    password: "{{ vixen_passwd }}"
    shell: /usr/bin/zsh

- name: users | vixen | create .ssh directory
  tags: dotfiles,vixen,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: vixen
    group: vixen
    mode: 0700
  with_items:
    - { dir: '/home/vixen/.ssh' }

- name: users | vixen | copy authorized_keys
  tags: users,vixen,ssh
  copy:
    src: users/vixen/authorized_keys
    dest: /home/vixen/.ssh/
    owner: vixen
    group: vixen
    mode: 0440

- name: users | shell | oh-my-zsh
  tags: users,vixen,zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: '/home/vixen/.oh-my-zsh'
    force: no
  become: yes
  become_user: vixen

- name: users | shell | powerlevel10k
  tags: user,vixen,zsh
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git/'
    dest: '/home/vixen/.oh-my-zsh/themes/powerlevel10k'
    depth: 1
  become: yes
  become_user: vixen

- name: users | shell | oh-my-tmux
  tags: user,vixen,tmux
  git:
    repo: 'https://github.com/gpakosz/.tmux.git'
    dest: '/home/vixen/GIT/oh-my-tmux'
  become: yes
  become_user: vixen

- name: users | shell | oh-my-config
  tags: user,vixen,zsh
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    owner: vixen
    group: vixen
    mode: 0755
  with_items:
      - { src: 'users/vixen/p10k.zsh', dest: '/home/vixen/.p10k.zsh' }
      - { src: 'users/vixen/zshrc', dest: '/home/vixen/.zshrc' }
      - { src: 'users/vixen/tmux.conf.local', dest: '/home/vixen/.tmux.conf.local' }
      - { src: 'users/vixen/tmux.conf', dest: '/home/vixen/.tmux.conf' }

- name: users | shell | powerlevel10k config
  tags: user,vixen,zsh
  lineinfile:
    path: '/home/vixen/.zshrc'
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME=powerlevel10k/powerlevel10k'

#- name: users | vixen | add public key
#  tags: dotfiles,vixen,ssh,ssh-keys,users
#  authorized_key:
#    user: vixen
#    key: "{{ item }}"
#  with_file:
#    - users/vixen/ssh/vixen_id_ed25519.pub
