- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  apt:
    state: latest
    name:
      - at
      - btop
      - colordiff
      - curl
      - dnsutils
      - iotop
      - lm-sensors
      - lsof
      - mc
      - mosh
      - ncdu
      - neofetch
      - net-tools
      - nfs-common
      - nmap
      - ranger
      - rename
      - rsync
      - screen
      - sshfs
      - tcpdump
      - tmux
      - traceroute
      - tree
      - tshark
      - vim-nox
      - wget
      - whois
      - zsh
