- name: system setup | repositories | add sources.list for debian hosts
  tags: non-free,repositories
  copy:
    src: distribution_packages/debian_sources.list
    dest: /etc/apt/sources.list
    backup: yes
  notify: apt_update
  when: ansible_distribution == "Debian"

