
- name: useful-scripts | /usr/local/bin/
  tags: sh,scripts
  copy:
    src: "scripts/{{ item.src }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: 'ls-stat.sh' }
    - { src: 'ipify' } 
    - { src: 'backlight' } 

- name: startup services
  tags: services
  copy:
    src: "scripts/{{ item.src }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: 'syncthing.service' }


- name: Enable syncthing
  ansible.builtin.systemd:
    name: syncthing
    enabled: yes
    masked: no
