- name: gaphor-deps
  tags: desktop, modelling, architecture, gaphor
  apt:
    name:
      - python3-dev 
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-4.0 
      - libgirepository1.0-dev 
      - libcairo2-dev
      - libgtksourceview-5-dev
      - libadwaita-1-dev
      - python3-pip
      - python3-venv
    state: latest

- name: gaphor
  ansible.builtin.pip:
    name: gaphor
    break_system_packages: true
    umask: "0022"
  become: true
