- name: desktop | suckless - ensure dependencies
  tags: desktop,suckless
  apt:
    pkg: 
      - dwm
      - suckless-tools
    state: build-dep


- name: desktop | suckless - get source
  tags: desktop,suckless,src
  git:
    repo: "https://git.suckless.org/{{ item }}"
    dest: /home/j4ck/GIT/suckless/{{ item }}
    force: yes
  register: gitclone
  with_items:
    - dwm
    - slock
    - dmenu
    - st
    - dwmstatus

- name: desktop | suckless | dwm | slock | dmenu
  tags: desktop,suckless,dwm,slock,dmenu
  become: true
  loop:
    - dwm
    - slock
    - dmenu
    - st
    - dwmstatus
  community.general.make:
    target: install
    chdir: "/home/j4ck/GIT/suckless/{{ item }}"
    make: /usr/bin/make
  when: gitclone.changed

