- name: desktop | nvidia drivers
  tags: desktop,nvidia,drivers,firmware
  when: inventory_hostname in groups['nvidia']
  apt:
    name: 
      - "linux-headers-{{ ansible_kernel }}"
      - nvidia-driver
      - firmware-misc-nonfree
    state: latest

- name: nvidia | run on discrete GPU
  tags: desktop,nvidia,GPU,script
  when: inventory_hostname in groups['nvidia']
  copy:
    src: scripts/nvidia-run.sh
    dest: /usr/local/bin/nvidia-run.sh
    owner: root
    group: root
    mode: 0755

- name: desktop | x11 | xorg | x server
  tags: desktop,x11,xorg,xserver
  apt:
    name: 
      - xserver-xorg-core
      - xserver-xorg-input-evdev
      - xserver-xorg-input-synaptics
      - x11-xserver-utils
      - x11-xkb-utils
      - x11-utils
      - xinit
      - suckless-tools
      - xdotool
      - feh

    state: latest
      
- name: desktop | lightdm,i3
  tags: desktop,i3
  apt:
    name: 
      - lightdm
      - i3-wm
      - i3

    state: latest
  when: inventory_hostname != "kitsune"

- name: desktop | gnome
  tags: desktop,gnome
  apt:
    name: 
      - gdm3
      - gnome
    state: latest
  when: inventory_hostname == "kitsune"

