- block:
  # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # install software
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_utilities.yml
  - import_tasks: software/useful_scripts.yml

  # Make sure users exist on the system
  - import_tasks: users/j4ck.yml
  - name: kitsune_base
      when: inventory_hostname == "kitsune"
      import_tasks: users/vixen.yml


  # Perform system setup tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/firmware.yml

  rescue:
    - set_fact: task_failed=true
