
- name: desktop | users | j4ck | fonts
  tags: desktop,users,j4ck,fonts
  copy:
    src: users/j4ck/fonts/
    dest: /home/j4ck/.fonts/
    owner: j4ck
    group: j4ck
    mode: 0440


- name: desktop | users | j4ck | dotfiles
  tags: desktop,users,j4ck,dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: j4ck
    group: j4ck
    mode: 0440
  with_items:
    - { src: 'users/j4ck/Xresources', dst: '/home/j4ck/.Xresources' }
    - { src: 'users/j4ck/Xdefaults', dst: '/home/j4ck/.Xdefaults' }
    - { src: 'users/j4ck/xinitrc', dst: '/home/j4ck/.xinitrc' }
    - { src: 'users/j4ck/xsession', dst: '/home/j4ck/.xsession' }


- name: desktop | users | j4ck | resources
  tags: desktop,users,j4ck,scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: j4ck
    group: j4ck
    mode: 0755
  with_items:
    - { src: 'users/j4ck/scripts/', dst: '/home/j4ck/.local/bin/' }
    - { src: 'users/j4ck/backgrounds/{{ inventory_hostname }}.jpg', dst: '/home/j4ck/.local/bg.jpg' }

- name: desktop | users | j4ck | i3-wm config
  ansible.builtin.lineinfile:
    path: /home/j4ck/.config/i3/config
    regexp: '^exec --no-startup-id feh.*'
    line: 'exec --no-startup-id feh --bg-center /home/j4ck/.local/bg.jpg'
#- name: desktop | users | j4ck | i3-wm config
#  ansible.builtin.blockinfile:
#    path: /home/j4ck/.config/i3/config



