
- name: desktop | users | j4ck | fonts
  tags: desktop,users,j4ck,fonts
  copy:
    src: users/j4ck/fonts/
    dest: /home/j4ck/.fonts/
    owner: j4ck
    group: j4ck
    mode: 0440


- name: desktop | users | j4ck | folders
  file:
    path: "{{ item.dir }}"
    state: directory
    mode: 0755
    owner: j4ck
    group: j4ck
  with_items:
    - { dir: '/home/j4ck/.config/i3' }
    - { dir: '/home/j4ck/.config/jgmenu/' }

- name: desktop | users | j4ck | dotfiles
  tags: desktop,users,j4ck,dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: j4ck
    group: j4ck
    mode: 0440
    force: no
  with_items:
    - { src: 'users/j4ck/Xdefaults', dst: '/home/j4ck/.Xdefaults' }
    - { src: 'users/j4ck/xinitrc', dst: '/home/j4ck/.xinitrc' }
    - { src: 'users/j4ck/xsession', dst: '/home/j4ck/.xsession' }
    - { src: 'users/j4ck/i3config', dst: '/home/j4ck/.config/i3/config' }
    - { src: 'users/j4ck/jgmenu/jgmenurc', dst: '/home/j4ck/.config/jgmenu/jgmenurc' }
    - { src: 'users/j4ck/jgmenu/append.csv', dst: '/home/j4ck/.config/jgmenu/append.csv' }

- name: desktop | users | j4ck | dotfiles
  tags: desktop,users,j4ck,dotfiles
  when: inventory_hostname not in groups['nvidia']
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: j4ck
    group: j4ck
    mode: 0440
    force: no
  with_items:
    - { src: 'users/j4ck/Xresources', dst: '/home/j4ck/.Xresources' }

- name: desktop | users | j4ck | dotfiles
  tags: desktop,users,j4ck,dotfiles
  when: inventory_hostname in groups['nvidia']
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: j4ck
    group: j4ck
    mode: 0440
    force: no
  with_items:
    - { src: 'users/j4ck/Xresources-mars', dst: '/home/j4ck/.Xresources' }

- name: desktop | users | j4ck | resources
  tags: desktop,users,j4ck,scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: j4ck
    group: j4ck
    mode: 0755
    force: no
  with_items:
    - { src: 'users/j4ck/scripts/', dst: '/usr/local/bin/' }
    - { src: 'users/j4ck/backgrounds/{{ inventory_hostname }}.png', dst: '/home/j4ck/.local/bg.png' }

- name: desktop | users | j4ck | i3-wm config
  ansible.builtin.lineinfile:
    path: /home/j4ck/.config/i3/config
    regexp: '^exec --no-startup-id feh.*'
    line: 'exec --no-startup-id feh --bg-center /home/j4ck/.local/bg.png'
#- name: desktop | users | j4ck | i3-wm config
#  ansible.builtin.blockinfile:
#    path: /home/j4ck/.config/i3/config



