- name: system setup | firmware 
  tags: system,firmware,non-free
  apt:
    name:
      - firmware-linux-nonfree
    state: latest
- name: system setup | wireless
  tags: system,firmware,wireless
  apt:
    name:
      - firmware-b43-installer
  when: inventory_hostname in groups['b43']
